const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];

const EX = {
 pullup:{name:'Trazioni presa prona',img:'assets/trazioni.png',weight:'corpo libero',rest:120,high:12,setup:'Scapole attive, addome contratto, gambe ferme. Parti in hang controllato, senza collassare sulle spalle.',grip:'Presa prona, poco più larga delle spalle.',con:'Tira il petto verso la sbarra e porta il mento sopra la barra.',ecc:'Scendi lentamente fino a quasi distendere i gomiti, mantenendo controllo scapolare.'},
 dbBench:{name:'Panca piana manubri',img:'assets/panca_piana.png',weight:'16 kg per mano',rest:90,high:12,setup:'Scapole addotte, piedi a terra, petto alto.',grip:'Presa neutra o semi-pronata, polsi dritti.',con:'Spingi i manubri verso l’alto, senza far perdere assetto alle spalle.',ecc:'Scendi lentamente finché senti allungamento sul petto.'},
 row1:{name:'Rematore 1 braccio',img:'assets/rematore1.png',weight:'18 kg',rest:90,high:12,setup:'Schiena neutra, petto aperto, busto stabile.',grip:'Presa neutra.',con:'Tira il gomito verso il fianco.',ecc:'Abbassa il manubrio in controllo fino ad allungare il dorsale.'},
 pushup:{name:'Push-up',img:'assets/pushup.png',weight:'corpo libero',rest:75,high:15,setup:'Corpo in linea, addome e glutei contratti.',grip:'Mani poco oltre la larghezza delle spalle.',con:'Spingi il pavimento e torna su.',ecc:'Scendi lentamente portando il petto verso il pavimento.'},
 lateral:{name:'Alzate laterali',img:'assets/alzate_laterali.png',weight:'6 kg per mano',rest:60,high:20,setup:'Busto fermo, spalle basse, addome attivo.',grip:'Presa neutra, gomiti leggermente piegati.',con:'Alza le braccia fino circa alla linea delle spalle.',ecc:'Scendi lentamente senza slancio.'},
 pushdown:{name:'Pushdown tricipiti con fune',img:'',weight:'12–18 kg sul cavo',rest:60,high:15,setup:'Gomiti vicini al busto, petto aperto, spalle basse.',grip:'Presa neutra sulla fune.',con:'Spingi la fune verso il basso distendendo i gomiti.',ecc:'Risalita controllata fino a riportare gli avambracci verso il petto.'},
 knee:{name:'Hanging knee raise',img:'',weight:'corpo libero',rest:60,high:15,setup:'Appenditi alla sbarra senza dondolare.',grip:'Presa comoda, prona o neutra.',con:'Porta le ginocchia verso il petto arrotolando leggermente il bacino.',ecc:'Distendi le gambe lentamente evitando slancio.'},
 goblet:{name:'Goblet squat',img:'assets/goblet_squat.png',weight:'24 kg',rest:90,high:15,setup:'Piedi poco oltre le spalle, punte leggermente fuori.',grip:'Manubrio stretto al petto.',con:'Spingi il pavimento e risali.',ecc:'Scendi con anche indietro e ginocchia in linea con i piedi.'},
 bulgarian:{name:'Bulgarian split squat',img:'assets/bulgarian_split_squat.png',weight:'8 kg per mano',rest:90,high:12,setup:'Piede anteriore saldo, busto leggermente inclinato.',grip:'Manubri ai lati o corpo libero.',con:'Spingi con il piede anteriore e risali.',ecc:'Scendi in controllo piegando anca e ginocchio.'},
 rdl:{name:'Romanian deadlift',img:'assets/rdl.png',weight:'18 kg per mano',rest:120,high:12,setup:'Schiena neutra, ginocchia morbide, anche indietro.',grip:'Presa neutra ai lati delle cosce.',con:'Spingi le anche avanti e torna in alto.',ecc:'Scendi facendo hip hinge, con i manubri vicino alle gambe.'},
 lunge:{name:'Affondi indietro',img:'',weight:'8 kg per mano',rest:75,high:10,setup:'Petto alto, passo indietro stabile.',grip:'Manubri ai lati o corpo libero.',con:'Spingi con il piede anteriore e torna in piedi.',ecc:'Scendi piegando entrambe le ginocchia in controllo.'},
 calf:{name:'Calf raise',img:'',weight:'corpo libero o 16 kg',rest:45,high:20,setup:'Appoggio stabile, caviglia in movimento completo.',grip:'Eventuale manubrio in una mano.',con:'Sali sulle punte e fai una pausa in alto.',ecc:'Scendi lentamente fino al massimo allungamento.'},
 plank:{name:'Plank',img:'',weight:'corpo libero',rest:45,high:75,setup:'Corpo in linea, addome e glutei attivi.',grip:'Avambracci a terra.',con:'Mantieni tensione e respira.',ecc:'Non collassare col bacino.'},
 pulldown:{name:'Lat machine / Pulldown',img:'',weight:'20–30 kg sul cavo',rest:90,high:15,setup:'Petto alto, leggera inclinazione indietro, spalle basse.',grip:'Presa prona o stretta neutra.',con:'Tira la barra verso la parte alta del petto.',ecc:'Rilascia lentamente fino ad allungare il dorsale.'},
 lowrow:{name:'Rematore al cavo basso',img:'',weight:'20–30 kg sul cavo',rest:75,high:15,setup:'Schiena neutra, petto aperto.',grip:'Presa stretta o neutra.',con:'Tira il manico verso l’ombelico.',ecc:'Ritorna lentamente in avanti senza perdere postura.'},
 shoulder:{name:'Shoulder press',img:'assets/shoulder_press.png',weight:'9 kg per mano',rest:90,high:12,setup:'Glutei e addome contratti, polsi neutri.',grip:'Presa neutra o leggermente prona.',con:'Spingi i manubri sopra la testa.',ecc:'Scendi lentamente fino all’altezza delle spalle.'},
 facepull:{name:'Face pull',img:'',weight:'8–12 kg sul cavo',rest:60,high:20,setup:'Petto alto, spalle lontane dalle orecchie.',grip:'Presa neutra sulla fune.',con:'Tira la fune verso il viso aprendo i gomiti.',ecc:'Ritorno lento senza perdere postura.'},
 curl:{name:'Curl con barra corta',img:'',weight:'10–14 kg totali',rest:60,high:12,setup:'Gomiti fermi, petto alto, niente slancio.',grip:'Presa supina.',con:'Fletti i gomiti e solleva la barra.',ecc:'Scendi lentamente fino quasi a distendere le braccia.'},
 reardelt:{name:'Rear delt fly',img:'',weight:'4–6 kg per mano',rest:60,high:20,setup:'Busto inclinato, schiena neutra.',grip:'Presa neutra.',con:'Apri le braccia in fuori stringendo dietro le spalle.',ecc:'Ritorna lentamente alla posizione iniziale.'},
 hip:{name:'Hip thrust / Glute bridge',img:'',weight:'24 kg',rest:90,high:15,setup:'Scapole su panca o schiena a terra, piedi alla larghezza delle anche.',grip:'Manubrio sul bacino.',con:'Spingi con i talloni e porta il bacino in alto.',ecc:'Scendi lentamente mantenendo tensione sui glutei.'},
 step:{name:'Step-up su panca',img:'',weight:'8 kg per mano',rest:75,high:12,setup:'Piede pienamente appoggiato sulla panca.',grip:'Manubri ai lati o corpo libero.',con:'Spingi con la gamba sulla panca e sali.',ecc:'Scendi lentamente senza cadere.'},
 legcurl:{name:'Sliding leg curl',img:'',weight:'corpo libero',rest:60,high:15,setup:'Supino, talloni su asciugamano o sliders.',grip:'Non prevista.',con:'Porta i talloni verso i glutei mantenendo il bacino alto.',ecc:'Distendi lentamente le gambe senza perdere il ponte.'},
 crunch:{name:'Cable crunch',img:'',weight:'12–18 kg sul cavo',rest:45,high:20,setup:'In ginocchio al cavo alto, bacino fermo.',grip:'Mani alla fune vicino alla testa.',con:'Fletti il busto verso il basso.',ecc:'Ritorna lentamente all’estensione controllata.'},
 pallof:{name:'Pallof press',img:'',weight:'6–10 kg sul cavo',rest:45,high:12,setup:'In piedi laterale al cavo, addome forte.',grip:'Due mani sulla maniglia.',con:'Spingi le mani avanti senza ruotare il busto.',ecc:'Riporta le mani al petto lentamente.'},
 incline:{name:'Panca inclinata 30° manubri',img:'assets/panca_piana.png',weight:'14 kg per mano',rest:90,high:12,setup:'Panca a 30°, scapole addotte, petto alto.',grip:'Presa neutra o semi-pronata.',con:'Spingi i manubri verso l’alto.',ecc:'Scendi lentamente senza perdere assetto.'},
 dip:{name:'Dip alle parallele',img:'assets/dip.png',weight:'corpo libero / assistito',rest:90,high:10,setup:'Spalle depresse, petto aperto, busto leggermente avanti.',grip:'Presa neutra sulle parallele.',con:'Spingi sulle parallele e distendi i gomiti.',ecc:'Scendi lentamente finché controlli petto e tricipiti.'}
};

const W = [
 {name:'Upper A — petto/schiena forza', items:[['pullup','4','6–10'],['dbBench','4','8–12'],['row1','4','8–12'],['pushup','3','quasi max'],['lateral','4','12–20'],['pushdown','3','10–15'],['knee','3','8–15']]},
 {name:'Lower A — quadricipiti/glutei', items:[['goblet','4','10–15'],['bulgarian','4','8–12 per gamba'],['rdl','4','8–12'],['lunge','3','10 per gamba'],['calf','4','12–20'],['plank','3','45–75 sec']]},
 {name:'Upper B — schiena/spalle', items:[['pullup','5','5–8'],['pulldown','4','10–15'],['lowrow','4','10–15'],['shoulder','4','8–12'],['facepull','3','12–20'],['curl','3','8–12'],['reardelt','3','12–20']]},
 {name:'Lower B — femorali/core', items:[['rdl','4','6–10'],['hip','4','10–15'],['step','3','8–12 per gamba'],['legcurl','3','8–15'],['calf','4','12–20'],['crunch','3','12–20'],['pallof','3','10–12 per lato']]},
 {name:'Upper C — petto/spalle/braccia', items:[['incline','4','8–12'],['pushup','4','8–15'],['pulldown','3','10–12'],['lowrow','3','10–12'],['lateral','4','12–20'],['dip','3','3–5 o assistite'],['curl','3','10–15'],['pushdown','3','10–15']]}
];

const D = [
 ['Giorno 1','Yogurt greco 250 g + pane 60 g + mela','Riso cotto 180 g + ceci 160 g + 10 g olio + frutta','Yogurt greco 170 g + banana','Pasta 80 g + 15 g pecorino + 2 uova + verdura minima/frutta'],
 ['Giorno 2','Yogurt greco 250 g + avena 40 g + pera','Pasta 80 g + ceci 140 g + pecorino 10 g','Frutta + 20 g frutta secca','Pollo/tacchino 180 g + polenta cotta 250 g + frutta'],
 ['Giorno 3','Yogurt greco 250 g + pane 60 g + marmellata leggera','Riso 180 g + lenticchie 160 g + 10 g olio','Yogurt 170 g + frutta','Omelette 3 uova + pane 70 g + frutta'],
 ['Giorno 4','Yogurt greco 250 g + avena 35 g + banana','Pasta 85 g + passata + pecorino 15 g + ceci 120 g','Pane 40 g + yogurt 170 g','Tacchino 160 g + patate 300 g o polenta 250 g + frutta'],
 ['Giorno 5','Yogurt greco 250 g + pane 60 g + kiwi','Riso 180 g + fagioli/ceci 160 g + 10 g olio','Frutta + yogurt 170 g','Pasta 75 g + ricotta/fiocchi di latte 150 g + pecorino 10 g'],
 ['Giorno 6','Yogurt greco 250 g + avena 40 g + mela','Pasta 80 g + ceci 160 g + pecorino 15 g','Frutta + 20 g mandorle','Uova 2 + albumi 200 g + pane 80 g + frutta'],
 ['Giorno 7','Yogurt greco 250 g + pane 60 g + frutta','Riso 180 g + pollo 160 g + 10 g olio','Yogurt 170 g + banana','Polenta 300 g + legumi 160 g + pecorino 10 g'],
 ['Giorno 8','Yogurt greco 250 g + avena 40 g + pera','Pasta 80 g + ceci 160 g + pecorino 15 g','Frutta + yogurt 170 g','Tacchino 180 g + pane 80 g + frutta'],
 ['Giorno 9','Yogurt greco 250 g + pane 60 g + mela','Riso 180 g + lenticchie 160 g + 10 g olio','Yogurt 170 g + frutta','Omelette 3 uova + polenta 250 g + frutta'],
 ['Giorno 10','Yogurt greco 250 g + avena 35 g + banana','Pasta 85 g + passata + pecorino 15 g','Frutta + 20 g frutta secca','Ceci 180 g + pane 80 g + yogurt greco 170 g'],
 ['Giorno 11','Yogurt greco 250 g + pane 60 g + frutta','Riso 180 g + pollo 160 g + 10 g olio','Yogurt 170 g + banana','Pasta 75 g + 2 uova + pecorino 10 g'],
 ['Giorno 12','Yogurt greco 250 g + avena 40 g + mela','Pasta 80 g + ceci 160 g + pecorino 15 g','Frutta + yogurt 170 g','Polenta 300 g + legumi 160 g + 10 g olio'],
 ['Giorno 13','Yogurt greco 250 g + pane 60 g + pera','Riso 180 g + fagioli/ceci 160 g','Yogurt 170 g + frutta','Tacchino 160 g + patate 300 g + frutta'],
 ['Giorno 14','Yogurt greco 250 g + avena 40 g + banana','Pasta 80 g + ceci 140 g + pecorino 15 g','Frutta + 20 g mandorle','Uova 2 + albumi 200 g + pane 70 g + frutta']
];
const mealNames=['Colazione','Pranzo','Spuntino','Cena'];

let seconds=90,left=90,tick=null,installPrompt=null;
const TKEY='ct_training_v2', MKEY='ct_measures_v2';
let training=JSON.parse(localStorage.getItem(TKEY)||'{}');
let measures=JSON.parse(localStorage.getItem(MKEY)||'[]');
function saveT(){localStorage.setItem(TKEY,JSON.stringify(training));renderProgress();}
function saveM(){localStorage.setItem(MKEY,JSON.stringify(measures));renderMeasures();}
function rec(id){if(!training[id]) training[id]={weight:EX[id].weight,notes:'',ready:false}; return training[id];}
function fmtTime(v){return String(Math.floor(v/60)).padStart(2,'0')+':'+String(v%60).padStart(2,'0')}
function setTimer(v){seconds=v;left=v;$('#timerValue').textContent=fmtTime(left);$$('.preset').forEach(b=>b.classList.toggle('active',+b.dataset.sec===v));}
function start(){clearInterval(tick);tick=setInterval(()=>{left--;$('#timerValue').textContent=fmtTime(left); if(left<=0){clearInterval(tick); if(navigator.vibrate) navigator.vibrate([200,100,200]); alert('Recupero finito. Prossima serie!');}},1000)}
function openScreen(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));}
function itemHTML(x){const [id,sets,reps]=x, e=EX[id], r=rec(id);return `<div class="exercise"><h4>${e.name}</h4><div class="meta"><span class="badge">${sets} serie</span><span class="badge">${reps}</span><span class="badge green">Rec. ${e.rest}s</span><span class="badge orange">${e.weight}</span></div><div class="btnrow"><button class="smallbtn tech" data-id="${id}">Tecnica</button><button class="smallbtn ghost rest" data-sec="${e.rest}">Timer</button><button class="smallbtn doneBtn ${r.ready?'done':'ghost'}" data-id="${id}">${r.ready?'Range completato':'Segna range'}</button></div></div>`}
function bind(root=document){root.querySelectorAll('.tech').forEach(b=>b.onclick=()=>showExercise(b.dataset.id));root.querySelectorAll('.rest').forEach(b=>b.onclick=()=>{setTimer(+b.dataset.sec);openScreen('timer');start()});root.querySelectorAll('.doneBtn').forEach(b=>b.onclick=()=>{const r=rec(b.dataset.id);r.ready=!r.ready;saveT();renderToday();renderWeek();});}
function renderToday(){const idx=+$('#daySelect').value||0;$('#todayName').textContent=W[idx].name;$('#todayList').innerHTML=W[idx].items.map(itemHTML).join('');bind($('#todayList'));}
function renderWeek(){const box=$('#weekPlan');box.innerHTML=W.map((d,i)=>`<div class="card day"><h2>${d.name}</h2><div class="list">${d.items.map(itemHTML).join('')}</div></div>`).join('');bind(box);}
function showExercise(id){const e=EX[id];$('#modalTitle').textContent=e.name;$('#modalBody').innerHTML=`${e.img?`<img class="modalImg" src="${e.img}" alt="${e.name}">`:''}<div class="techgrid"><div class="techblock"><h4>Impostazione</h4><p>${e.setup}</p></div><div class="techblock"><h4>Impugnatura</h4><p>${e.grip}</p></div><div class="techblock"><h4>Concentrica</h4><p>${e.con}</p></div><div class="techblock"><h4>Eccentrica</h4><p>${e.ecc}</p></div></div><div class="techblock"><h4>Peso iniziale e progressione</h4><p><b>Peso:</b> ${e.weight}<br><b>Recupero:</b> ${e.rest}s</p><p class="note">Quando completi tutte le serie al massimo del range con tecnica pulita, aumenta il carico nella seduta successiva. Per manubri: +2 kg per mano se disponibile; per cavi: +2,5–5 kg; per corpo libero: più ripetizioni o piccola zavorra.</p></div>`;$('#modal').showModal();}
function renderLibrary(f=''){const ids=Object.keys(EX).filter(id=>EX[id].name.toLowerCase().includes(f.toLowerCase()));$('#library').innerHTML=ids.map(id=>{const e=EX[id];return `<div class="card lib">${e.img?`<img src="${e.img}" alt="${e.name}">`:`<div class="techblock"><b>Immagine non ancora presente</b><p class="note">Le istruzioni tecniche sono comunque disponibili.</p></div>`}<h3>${e.name}</h3><div class="meta"><span class="badge orange">${e.weight}</span><span class="badge green">${e.rest}s</span></div><button class="tech" data-id="${id}">Apri tecnica</button></div>`}).join('');bind($('#library'));}
function renderProgress(){const ids=Object.keys(EX);$('#progressList').innerHTML=ids.map(id=>{const e=EX[id], r=rec(id);const cls=r.ready?'up':'keep';const sug=r.ready?'Aumenta il peso':'Mantieni / aggiungi reps';return `<div class="progRow"><div><b>${e.name}</b><div class="note">inizio: ${e.weight}</div></div><input data-id="${id}" data-f="weight" value="${r.weight||''}" placeholder="peso attuale"><input data-id="${id}" data-f="notes" value="${r.notes||''}" placeholder="note/reps"><div class="suggest ${cls}">${sug}</div></div>`}).join('');$('#progressList').querySelectorAll('input').forEach(inp=>inp.onchange=()=>{const r=rec(inp.dataset.id);r[inp.dataset.f]=inp.value;saveT();});}
function renderDiet(){ $('#dietPlan').innerHTML=D.map(d=>`<div class="card dietday"><h3>${d[0]}</h3>${d.slice(1).map((m,i)=>`<div class="meal"><b>${mealNames[i]}</b>${m}</div>`).join('')}<p class="note">Acqua, caffè/tè senza zucchero ok. Verdura minima: prova passata, zucchine, carote o insalata semplice anche in piccole quantità.</p></div>`).join('') + `<div class="card"><h3>Sostituzioni veloci</h3><p><b>Carboidrati equivalenti:</b> pasta 80 g ≈ riso cotto 220–240 g ≈ pane 100 g ≈ polenta cotta 300 g ≈ avena 70 g.</p><p><b>Proteine:</b> yogurt greco, uova/albumi, legumi, pollo/tacchino, ricotta magra o fiocchi di latte se li usi. Pecorino: meglio 10–15 g come condimento, non come fonte proteica principale.</p></div>`;}
function addMeasure(){const date=$('#mDate').value || new Date().toISOString().slice(0,10); const weight=parseFloat($('#mWeight').value); const waist=parseFloat($('#mWaist').value); if(!weight&&!waist){alert('Inserisci almeno peso o girovita');return;} measures.push({date,weight,waist}); measures.sort((a,b)=>a.date.localeCompare(b.date)); saveM(); $('#mWeight').value='';$('#mWaist').value='';}
function renderMeasures(){const list=$('#measureList');list.innerHTML=measures.slice().reverse().map((m,i)=>`<div class="measureRow"><b>${m.date}</b><span>${m.weight?m.weight+' kg':'—'}</span><span>${m.waist?m.waist+' cm':'—'}</span><button class="ghost smallbtn delM" data-i="${measures.length-1-i}">Elimina</button></div>`).join('');list.querySelectorAll('.delM').forEach(b=>b.onclick=()=>{measures.splice(+b.dataset.i,1);saveM();});drawChart();}
function drawChart(){const c=$('#measureChart'), ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#f8fafc';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#dbe5ef';ctx.lineWidth=2;for(let i=0;i<5;i++){let y=40+i*65;ctx.beginPath();ctx.moveTo(50,y);ctx.lineTo(c.width-20,y);ctx.stroke();}if(measures.length<2){ctx.fillStyle='#64748b';ctx.font='24px sans-serif';ctx.fillText('Aggiungi almeno 2 misure per vedere il grafico',60,180);return;}const xs=measures.map((_,i)=>50+i*(c.width-80)/(measures.length-1));function plot(key,color,label,off){const vals=measures.map(m=>m[key]).filter(v=>v);if(vals.length<2)return;const all=measures.map(m=>m[key]||null);const min=Math.min(...vals),max=Math.max(...vals);ctx.strokeStyle=color;ctx.lineWidth=5;ctx.beginPath();let started=false;all.forEach((v,i)=>{if(!v)return;const y=300-(v-min)/(max-min||1)*220; if(!started){ctx.moveTo(xs[i],y);started=true}else ctx.lineTo(xs[i],y)});ctx.stroke();ctx.fillStyle=color;ctx.font='22px sans-serif';ctx.fillText(label,60,30+off);}plot('weight','#2563eb','Peso',0);plot('waist','#16a34a','Vita',26);}
function init(){W.forEach((w,i)=>$('#daySelect').insertAdjacentHTML('beforeend',`<option value="${i}">${w.name.split('—')[0].trim()}</option>`));$('#daySelect').onchange=renderToday;renderToday();renderWeek();renderLibrary();renderProgress();renderDiet();$('#mDate').value=new Date().toISOString().slice(0,10);renderMeasures();$$('.nav button').forEach(b=>b.onclick=()=>openScreen(b.dataset.screen));$('#search').oninput=e=>renderLibrary(e.target.value);$$('.preset').forEach(b=>b.onclick=()=>setTimer(+b.dataset.sec));$('#startTimer').onclick=start;$('#pauseTimer').onclick=()=>clearInterval(tick);$('#resetTimer').onclick=()=>setTimer(seconds);$('#closeModal').onclick=()=>$('#modal').close();$('#addMeasure').onclick=addMeasure;$('#resetTraining').onclick=()=>{if(confirm('Azzero il diario esercizi?')){training={};localStorage.removeItem(TKEY);renderProgress();renderToday();renderWeek();}};$('#resetMeasures').onclick=()=>{if(confirm('Azzero tutte le misure?')){measures=[];localStorage.removeItem(MKEY);renderMeasures();}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').classList.remove('hidden');});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').classList.add('hidden')}};if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js').catch(()=>{});}}
init();
